config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

   scope module: :public do

  root to:"homes#top"
  get "/about"=>"homes#about", as:"about"

    resources :items,only: [:index,:show,:edit]
    resource :customers,only: [:show] do
      collection do
        get'/mypage' =>"customers#show"
        get'/information/edit' =>"customers#edit"
        patch'/information' =>"customers#update"
        get'unsubscribe' =>"customers#unsubscribe"
        patch 'withdraw'=>"customers#withdraw"
      end
    end

    resources :cart_items,only: [:index,:update,:destroy,:create] do
      collection do
        delete'destroy_all'
      end
    end

    resources :orders,only: [:new,:create,:index,:show] do
      collection do
        post'confirm'
        get'complete'
      end
    end

    resources :addresses,only: [:index,:edit,:create,:update,:destroy]
  end

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

   namespace :admin do
    root to:"orders#index"
    resources :items
    resources :genres,only: [:index,:create,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show,:update]
    resources :order_items,only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
   
   
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  def add_tax_price
    (self.price * 1.1).round
  end

  def sum_of_price
      item.add_tax_price*amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def add_tax_price
    (self.price * 1.1).round
  end

  def get_image(width,height)
     unless image.attached?
        file_path= Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
     end
     image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status:{ waiting_for_payment: 0, payment_confirmation:1, in_production:2, preparing_to_ship:3, sent:4 }
  
 
  def get_amount
      amount=0
      order_items.each do |order_item|
      amount += order_item.amount
    end 
    amount
  end 
  
  def get_image
     unless image.attached?
        file_path= Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
     end 
     image
  end 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  enum making_status:{ cannot_be_manufactured:0, waiting_for_production:1, in_production:2, completion_of_production:3}
  
   def add_tax_price
  (self.price * 1.1).round
  end 

  def sum_of_price
      item.add_tax_price*amount
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers=Customer.page(params[:page])
  end 
  
  def show
    @customer=Customer.find(params[:id])
  end 
  
  def edit
    @customer=Customer.find(params[:id])
  end
  
  def update
    @customer=Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end 
  
  private
  def customer_params
   params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:encrypted_password,:postal_code,:address,:telephone_number,:is_deleted)
  end 
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre=Genre.new
    @genres=Genre.all
  end 
  
  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end 
  
  def edit
    @genre=Genre.find(params[:id])
  end 
  
  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end 

private

def genre_params
  params.require(:genre).permit(:name)
end 

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def new
    @item=Item.new
    @genres=Genre.all
    end
  
    def create
    @item=Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
    end 
  
  def index
    @items=Item.page(params[:page])
    
  end 
  
  def show
    @item=Item.find(params[:id])
  end 
  
  def edit
    @genres=Genre.all
    @item=Item.find(params[:id])
  end 
  
  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def update
   @order=Order.find(params[:id])
   @order_items=OrderItem.where(order_id: params[:id])
  if @order.update(order_params)
     @order_items.update_all(making_status: 1) if @order.status == "payment_confirmation"
  end
  redirect_to admin_order_path(@order)
  end 
  
  def index
   @orders=Order.page(params[:page])
  end 
  
  def show
   @order=Order.find(params[:id])
   @total=@order.order_items.inject(0) { |sum, item| sum + item.sum_of_price }
  end 
  
  private
  def order_params
  params.require(:order).permit(:customer_id,:postal_code,:address,:name,:payment_method,:total_payment,:shipping_cost,:status)
  end 
end 

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller? 

def after_sign_in_path_for(resource)
  case resource
  when Admin
      admin_root_path
  when Customer
      mypage_customers_path
  end 
end

def after_sign_out_path_for(resource)
  case resource
  when :admin
      admin_session_path
  when :customer
      root_path
  end
end 

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number]) 
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
  <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
  </div>

  <%= form_with model: @customer, url: admin_customer_path(@customer),method: :patch do |f| %>
  
  <div class="row mt-5">
  <h6>会員ID</h6>
  <div style="padding-left :100px;"><%= @customer.id %></div>
  </div>
  
  <div class="row mt-2">
  <h6>氏名</h6>
  <div style="padding-left :115px;"><%= f.text_field :last_name %> <%= f.text_field :first_name %></div>
  </div>
  
  <div class="row mt-2">
  <h6>フリガナ</h6>
  <div style="padding-left :83px;"><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></div>
  </div>
  
  <div class="row mt-2">
  <h6>郵便番号</h6>
  <div style="padding-left :83px;"><%= f.text_field :postal_code %></div>
  </div>

 <div class="row mt-2">
 <h6>住所</h6>
 <div style="padding-left :115px;"><%= f.text_field :address,size: 50 %></div>
 </div>

 <div class="row mt-2">
 <h6>電話番号</h6>
 <div style="padding-left :83px;"><%= f.text_field :telephone_number %></div>
 </div>

 <div class="row mt-2">
 <h6>メールアドレス</h6>
 <div style="padding-left :35px;"><%= f.text_field :email %></div>
 </div>

 <div class="row mt-2">
 <h6>会員ステータス</h6>
 <div style="padding-left :35px;"><%= f.radio_button :is_deleted, "有効", checked:true %>有効 <%=f.radio_button :is_deleted, "退会" %>退会</div>
 </div>

 <div class="row mt-5">
 <%= f.submit '変更を保存',class:"btn btn-success" %>
 </div>
 <% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
  <h2>会員一覧</h2>
  </div>
  
  <table class="table mt-5">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to admin_customer_path(customer.id) do %>
            <%= customer.last_name %><%= customer.first_name %>
            <% end %></td>
        <td><%= customer.email %></td>
        <td><p class="<%= customer.is_deleted ? "text-danger" : "text-success" %>"><%= customer.is_deleted ? '退会':'有効' %></p></td>
      </tr>
  <% end %>
    </thead>
  </table>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
  <h2><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
  </div>
  
  <div class="row mt-5">
  <h6>会員ID</h6>
  <div style="padding-left :100px;"><%= @customer.id %></div>
  </div>

　<div class="row">
  <h6>氏名</h6>
  <div style="padding-left :115px;"><%= @customer.last_name %><%= @customer.first_name %></div>
  </div>

　<div class="row">
  <h6>フリガナ</h6>
  <div style="padding-left :80px;"><%= @customer.last_name_kana %><%= @customer.first_name_kana %></div>
  </div>

　<div class="row">
  <h6>郵便番号</h6>
  <div style="padding-left :80px;"><%= @customer.postal_code %></div>
  </div>

　<div class="row">
  <h6>住所</h6>
  <div style="padding-left :110px;"><%= @customer.address %></div>
  </div>

　<div class="row">
  <h6>電話番号</h6>
  <div style="padding-left :78px;"><%= @customer.telephone_number %></div>
  </div>
  
  <div class="row mt-3">
  <h6>メールアドレス</h6>
  <div style="padding-left :32px;"><%= @customer.email %></div>
  </div>
  
  <div class="row mt-3">
  <h6>会員ステータス</h6>
  <div style="padding-left :32px;"><p class="<%= @customer.is_deleted ? "text-danger" : "text-success" %>"><%= @customer.is_deleted ? '退会':'有効' %></p></div>
  </div>

  <div class="row">
  <div class="mt-5">
    <%= link_to "編集する",edit_admin_customer_path(@customer.id),class:"btn btn-success" %>
  </div>
  <div class="mt-5 ml-5">
    <%= link_to "注文履歴一覧を見る", admin_root_path,class:"btn btn-primary" %>
  </div>
  </div>
  
</div>