config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

   scope module: :public do

  root to:"homes#top"
  get "/about"=>"homes#about", as:"about"

    resources :items,only: [:index,:show,:edit]
    resource :customers,only: [:show] do
      collection do
        get'/mypage' =>"customers#show"
        get'/information/edit' =>"customers#edit"
        patch'/information' =>"customers#update"
        get'unsubscribe' =>"customers#unsubscribe"
        patch 'withdraw'=>"customers#withdraw"
      end
    end

    resources :cart_items,only: [:index,:update,:destroy,:create] do
      collection do
        delete'destroy_all'
      end
    end

    resources :orders,only: [:new,:create,:index,:show] do
      collection do
        post'confirm'
        get'complete'
      end
    end

    resources :addresses,only: [:index,:edit,:create,:update,:destroy]
  end

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

   namespace :admin do
    root to:"orders#index"
    resources :items
    resources :genres,only: [:index,:create,:edit,:update]
    resources :customers,only: [:index,:show,:edit,:update]
    resources :orders,only: [:show,:update]
    resources :order_items,only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :customer
   
   
   def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
   end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer


  def add_tax_price
    (self.price * 1.1).round
  end

  def sum_of_price
      item.add_tax_price*amount
  end


end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
   has_one_attached :image
  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def add_tax_price
    (self.price * 1.1).round
  end

  def get_image(width,height)
     unless image.attached?
        file_path= Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
     end
     image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status:{ waiting_for_payment: 0, payment_confirmation:1, in_production:2, preparing_to_ship:3, sent:4 }
  
 
  def get_amount
      amount=0
      order_items.each do |order_item|
      amount += order_item.amount
    end 
    amount
  end 
  
  def get_image
     unless image.attached?
        file_path= Rails.root.join('app/assets/images/no_image.jpg')
        image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type: 'image/jpeg')
     end 
     image
  end 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  enum making_status:{ cannot_be_manufactured:0, waiting_for_production:1, in_production:2, completion_of_production:3}
  
   def add_tax_price
  (self.price * 1.1).round
  end 

  def sum_of_price
      item.add_tax_price*amount
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre=Genre.new
    @genres=Genre.all
  end 
  
  def create
    @genre=Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end 
  
  def edit
    @genre=Genre.find(params[:id])
  end 
  
  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end 

private

def genre_params
  params.require(:genre).permit(:name)
end 

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def new
    @item=Item.new
    @genres=Genre.all
    end
  
    def create
    @item=Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
    end 
  
  def index
    @items=Item.page(params[:page])
    
  end 
  
  def show
    @item=Item.find(params[:id])
  end 
  
  def edit
    @genres=Genre.all
    @item=Item.find(params[:id])
  end 
  
  def update
    @item=Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end
  
  private
  def item_params
    params.require(:item).permit(:genre_id,:name,:introduction,:price,:is_active,:image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller? 

def after_sign_in_path_for(resource)
  case resource
  when Admin
      admin_root_path
  when Customer
      mypage_customers_path
  end 
end

def after_sign_out_path_for(resource)
  case resource
  when :admin
      admin_session_path
  when :customer
      root_path
  end
end 

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number]) 
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg">
      <div class="container">
      <% if customer_signed_in? %>

      <ul class="navbar-nav ml-auto">
        <p class="mr-5">ようこそ、<%= current_customer.last_name %>さん！</p>
        <li class="nav-item mr-3"><%= link_to "マイページ", mypage_customers_path %></li>

        <li class="nav-item mr-3"><%= link_to "商品一覧",items_path %></li>

        <li class="nav-item mr-3"><%= link_to "カート",cart_items_path %></li>

        <li class="nav-item mr-3"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete %></li>

      </ul>

      <% elsif admin_signed_in? %>
      <ul class="navbar-nav ml-auto">
       <li class="nav-item mr-3"><%= link_to "商品一覧", admin_items_path %></li>

       <li class="nav-item mr-3"><%= link_to "会員一覧", admin_customers_path %></li>

       <li class="nav-item mr-3"><%= link_to "注文履歴一覧",admin_root_path %></li>

       <li class="nav-item mr-3"><%= link_to "ジャンル一覧", admin_genres_path %></li>

       <li class="nav-item mr-3"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
      </ul>

     <% else %>
      <ul class="navbar-nav ml-auto">
       <li class="nav-item mr-3"><%= link_to "About", about_path %></li>

       <li class="nav-item mr-3"><%= link_to "商品一覧", items_path %></li>

       <li class="nav-item mr-3"><%= link_to "新規登録", new_customer_registration_path %></li>

       <li class="nav-item mr-3"><%=link_to "ログイン", new_customer_session_path %></li>
     </ul>
    <% end %>
    </div>
    </nav>
   </header>

    <%= yield %>
  </body>
</html>